import {Metadata} from "next";
import HomePageTabs from "@/components/home_page_tabs";
import api from "@/api";
import ContextMenu from "./components/cm";

export const metadata: Metadata = {
  title: "聚合搜索",
  description: "Generated by create next app",
};
export default async function Page() {
  const tabs = await api.searchor();
  return (
    <main className="container mx-auto flex-auto z-1">
      <HomePageTabs tabs={tabs.data || []} />
      <hr />
      <ContextMenu>xxx</ContextMenu>
    </main>
  );
}
