import {Metadata} from "next";
import YouNongPaiToken from "./token";


export const metadata: Metadata = {
  title: "优农派",
  description: "Generated by create next app",
};

export default async function YouNongPaiPage() {
  return (
    <main className="container mx-auto flex-auto z-1">
      <YouNongPaiToken />
    </main>
  )
}